### ISSUE TITLE
七牛api包地址变了。

### ISSUE THREAD

**Issue by fmnisme** [UlricQin/beego-blog#5]
多了个`.v6`:
`github.com/qiniu/api.v6`

**Comment by bingoHuang** [comment]
是的，我执行go get github.com/ulricqin/beego-blog/... 也遇到如下错误：
package github.com/qiniu/api/conf: cannot find package "github.com/qiniu/api/conf" in any of:
	/mydata/local/go/src/github.com/qiniu/api/conf (from $GOROOT)
	/mydata/App/Go/src/github.com/qiniu/api/conf (from $GOPATH)
package github.com/qiniu/api/io: cannot find package "github.com/qiniu/api/io" in any of:
	/mydata/local/go/src/github.com/qiniu/api/io (from $GOROOT)
	/mydata/App/Go/src/github.com/qiniu/api/io (from $GOPATH)
package github.com/qiniu/api/rs: cannot find package "github.com/qiniu/api/rs" in any of:
	/mydata/local/go/src/github.com/qiniu/api/rs (from $GOROOT)
	/mydata/App/Go/src/github.com/qiniu/api/rs (from $GOPATH)

我已提PR（https://github.com/UlricQin/beego-blog/pull/7），请作者看看如何可以接收修改

**Comment by UlricQin** [comment]
#7
