### ISSUE TITLE
when  go get the beego-blog/...  get error and dont know whats meaning

### ISSUE THREAD

**Issue by WangWenchao** [UlricQin/beego-blog#8]
go 1.6
bee 1.4.2

```
➜  ulricqin$  go get github.com/ulricqin/beego-blog/...
# github.com/ulricqin/beego-blog/g
beego-blog/g/cache.go:9: cannot use blogCacheExpire (type int64) as type time.Duration in argument to Cache.Put
beego-blog/g/cache.go:13: cannot use catalogCacheExpire (type int64) as type time.Duration in argument to Cache.Put
beego-blog/g/g.go:45: undefined: orm.DR_MySQL
```

any help pls. tkx

**Comment by johnstevin** [comment]
同样求问，感谢！

![qq 20160420183606](https://cloud.githubusercontent.com/assets/7678086/14671854/c4bd78a4-0726-11e6-8785-26197b7e28d5.png)

**Comment by sugaofeng** [comment]
同样的问题

**Comment by iamwujian** [comment]
我解决了。按提示的错误检查可以解决问题

**Comment by IT-BB** [comment]
@iamwujian 你是怎么解决的呢？

**Comment by iamwujian** [comment]
具体你尝试自己去解决吧。我跟你说是哪里出了问题。

一共返回了三个错误对吧。
前两个是一样的，beego升级之后（还是Go升级之后？我忘记了），总之，是那个函数的传入参数的类型改了，以前是int64，现在是time.Duration。你改一下源码就行。
第三个错误，也是升级之后，ServeJson改名为ServeJSON了。改一下函数名字就好。

不懂再邮件联系吧。
（当你改好之后你会发现……这个博客bug多得不值得你一看）



 
From: kangdandan
Date: 2016-07-28 16:58
To: UlricQin/beego-blog
CC: iamwujian; Mention
Subject: Re: [UlricQin/beego-blog] when go get the beego-blog/... get error and dont know whats meaning (#8)
@iamwujian 你是怎么解决的呢？

**Comment by aleafboat** [comment]
> //blogCacheExpire, _ = Cfg.Int64("blog_cache_expire")
>         blogCacheExpire = time.Duration(10000000000) 还是不行呀

**Comment by AAA-AA** [comment]
昨天刚好解决了，其实都还算是比较容易的，现在贴出相应的解决办法
正如楼上所说的，其实究其原因，应该是升级后未进行完整调试运行导致的。报错的提示是类型不匹配，进行强转一下即可
`time.Duration(blogCacheExpire)`，另外相同的报错也是同样处理
另外的报错，楼上已经解答了。如果还有人没能解决，欢迎「骚扰」/doge脸

**Comment by UlricQin** [comment]
@iamwujian  "当你改好之后你会发现……这个博客bug多得不值得你一看" 搞得我都不好意思了...
其实主要问题是beego升级之后api不兼容了，这个blog的代码写的很早，基于一个比较老的beego。
我来改一下吧，至少编译通过：）

**Comment by UlricQin** [comment]
好了，根据beego的最新api更新了一下，变化不大，只是beego的一些function和field的rename。并且把beego作为vendor加入项目代码中，以后不怕向后不兼容的问题了
