### ISSUE TITLE
小白问题

### ISSUE THREAD

**Issue by MerlinFeng** [UlricQin/beego-blog#9]
2016/07/28 18:30:43 [ERRO] ============== Build failed ===================
2016/07/28 18:31:01 [EVEN] "E:\gopath\src\github.com\ulricqin\beego-blog\g\cache.go": MODIFY
2016/07/28 18:31:01 [SKIP] "E:\gopath\src\github.com\ulricqin\beego-blog\g\cache.go": MODIFY
2016/07/28 18:31:01 [SKIP] "E:\gopath\src\github.com\ulricqin\beego-blog\g\cache.go": MODIFY
2016/07/28 18:31:01 [SKIP] "E:\gopath\src\github.com\ulricqin\beego-blog\g\cache.go": MODIFY
2016/07/28 18:31:01 [SKIP] "E:\gopath\src\github.com\ulricqin\beego-blog\g\cache.go": MODIFY
2016/07/28 18:31:01 [SKIP] "E:\gopath\src\github.com\ulricqin\beego-blog\g\cache.go": MODIFY
2016/07/28 18:31:02 [INFO] Start building...
# github.com/ulricqin/beego-blog/g

g\cache.go:9: cannot use blogCacheExpire (type int64) as type time.Duration in argument to Cache.Put
g\cache.go:13: cannot use catalogCacheExpire (type int64) as type time.Duration in argument to Cache.Put
g\g.go:46: undefined: orm.DR_MySQL
2016/07/28 18:31:03 [ERRO] ============== Build failed ===================

**Comment by aleafboat** [comment]
`我也遇到哦同样问题  modify conf/app.conf 执行失败 没有这个命令 你遇到了吗`

**Comment by aleafboat** [comment]
# github.com/ulricqin/beego-blog/g
g/cache.go:9: cannot use blogCacheExpire (type int64) as type time.Duration in argument to Cache.Put
g/cache.go:13: cannot use catalogCacheExpire (type int64) as type time.Duration in argument to Cache.Put
g/g.go:45: undefined: orm.DR_MySQL
2016/08/06 14:30:26 [ERRO] ============== Build failed ===================

**Comment by UlricQin** [comment]
这个blog代码是基于beego的一个老版本开发的，beego新版本api不兼容，已经更正：）
modify conf/app.conf不是个命令 @aleafboat  是说让使用者自行修改一下配置文件，比如数据库连接地址之类的

**Comment by MerlinFeng** [comment]
thank you very much; 已经解决！
